name: Test UDP Server

on:
  push:
  pull_request:

jobs:
  test-udp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files (debug)
        run: ls -l

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run UDP server in background
        run: |
          python udp_server.py &
          sleep 2  # give server time to start

      - name: Run UDP client test
        run: python udp_client.py

      - name: Kill UDP server
        run: pkill -f udp_server.py || true
