name: UDP Server Run

on:
  workflow_dispatch:  # manual trigger

jobs:
  udp-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Show runner public IP
        run: curl ifconfig.me

      - name: Start UDP server in background
        run: |
          python udp_server.py &
          sleep 2  # allow server to start

      - name: Run UDP client test
        run: python udp_client.py

      - name: Keep server running (sleep infinite)
        run: |
          echo "UDP server started, runner will stay alive..."
          sleep infinity
