
name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  Run-PSScriptAnalyzer-on-Windows:
    name: Run PSScriptAnalyzer on Windows
    runs-on: windows-2019
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install PSScriptAnalyzer module
      shell: pwsh
      run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop
    - name: Get list of rules
      shell: pwsh
      run: |
          Get-ScriptAnalyzerRule
    - name: Initialize setup
      run: ./setup.ps1
    - name: Start CRD 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep alive
      run: ./timeout.ps1
