name: Windows-CRD

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true

jobs:
  Run-PSScriptAnalyzer-on-Windows:
    name: Run PSScriptAnalyzer on Windows
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install PSScriptAnalyzer module
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module PSScriptAnalyzer -ErrorAction Stop

    - name: Get list of rules
      shell: pwsh
      run: Get-ScriptAnalyzerRule

    - name: Initialize setup
      run: ./setup2.ps1

    - name: Start CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}

    - name: Initialize setup clean
      run: ./clean.ps1

    - name: Keep alive
      shell: pwsh
      run: ./timeout.ps1

  Upload-Project:
    name: Upload Android Project
    needs: Run-PSScriptAnalyzer-on-Windows
    if: always() # This ensures the job runs even if the previous one is cancelled.
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Upload project from runner
      run: |
        git config --global user.name "ROOTgit123"
        git config --global user.email "khadijdija32@gmail.com"
        git add C:\Users\runneradmin\StudioProjects\*
        git commit -m "Add Android Studio project files"
        git push
