# This is a basic workflow to help you get started with Actions

name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: '& "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AWgavddPZP8OmplzmNULbtAadsda8pS4HwsAFunQMVzQkBb6-feTA0ARevLMfbEWK_JeDg" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME'
        required: true
      pincode:
        description: '123123'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
      timeout-minutes: 90
    - name: Keep Alive
      run: ./timeout.ps1