# This is a basic workflow to help you get started with Actions

name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: '& "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AWgavddPZP8OmplzmNULbtAadsda8pS4HwsAFunQMVzQkBb6-feTA0ARevLMfbEWK_JeDg" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME'
        required: true
      pincode:
        description: '123123'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        choco install -y visualstudio2019buildtools
        choco install -y dotnetcore-sdk
    - name: Build RDP
      run: |
        dotnet build --configuration Release
    - name: Package RDP
      run: |
        dotnet publish --configuration Release --output package
    - name: Archive package
      run: |
        7z a rdp-windows.zip package
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: rdp-windows
        path: rdp-windows.zip
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
      timeout-minutes: 90
    - name: Keep Alive
      run: ./timeout.ps1
